### ISSUE TITLE
I can't find the .exe in the folder that the tool specifies 

### ISSUE THREAD

**Issue by spyhunyter** [Tech-Sec/WinPyLogger#1]
I can't find the .exe in the folder that the tool specifies

**Comment by Tech-Sec** [comment]
It's in the dist folder under main folder which the tool generated.

**Comment by Tech-Sec** [comment]
> I can't find the .exe in the folder that the tool specifies 

It's in the dist folder under the main folder which the tool generates.

**Comment by spyhunyter** [comment]
Inside the dist folder is an executable, how do I put it on the target machine? The target machine is win, please I ask you to guide me because I am lost

**Comment by Tech-Sec** [comment]
> Inside the dist folder is an executable, how do I put it on the target machine? The target machine is win, please I ask you to guide me because I am lost

Yeah it is the executable which is the keylogger. You can send it through many ways. This might help you out. [Social Engineering](https://www.csoonline.com/article/2124681/what-is-social-engineering.html)

**Comment by spyhunyter** [comment]
what I wanted to ask is the following: how is the .exe installed?, I did the test in windows 10 and also in windows 7, both 64-bit, and I get the error that indicates that windows can not run programs in 16 bits, so I ask how to install the .exe?, I am grateful for your answer.

**Comment by Tech-Sec** [comment]
> 
> 
> what I wanted to ask is the following: how is the .exe installed?, I did the test in windows 10 and also in windows 7, both 64-bit, and I get the error that indicates that windows can not run programs in 16 bits, so I ask how to install the .exe?, I am grateful for your answer.

Follow the instructions in the README file. I tested it again on Windows 10. It worked smoothly.
